### ISSUE TITLE
Discord Store library support

### ISSUE THREAD

**Issue by JosefNemec** [JosefNemec/Playnite#854]

**Comment by bburky** [comment]
See notes on API in discord: https://discordapp.com/channels/365863063296933888/366310563774464000/547524300928712705

Here is a proof of concept extension to import installed Discord games: https://gist.github.com/bburky/43e666b2f6bb6db4c42b5ecd93f7af38

Uninstalled games should be available from the `https://discordapp.com/api/v6/users/@me/library` API endpoint.

**Comment by bburky** [comment]
`https://discordapp.com/api/v6/users/@me/library` Authenticated API endpoint returning all owned games. Requires an `Authorization:` header with a token. Token can be from either webapp or desktop app.

`https://discordapp.com/api/v6/applications` Listing of all games, but also includes non-store games. Useful for some metadata and mapping "application ids" to "sku ids".

`https://discordapp.com/api/v6/store/published-listings/skus/488607666231443456` Indivdual store listing. Has a lot of metadata. Application metadata is also duplicated under the `sku` key. The only useful but unknown field is genre, which has unknown genre id numbers.

`discord:///library/460940655984771072/launch` Game launch URL. `discord:///library/460940655984771072/uninstall Game uninstall URL. These URLs use the application id, not the sku id. I have not found an install URL format.

The token isn't easily extracted from the installed desktop app, it is in localstorage. Instead probably do an authentication flow in Playnite with a browser and extract the token. Haven't looked at authentication yet.

`InstallationManagerStore` exists in localstorage of the installed app, but it's probably easier to use Playnite's `Programs.GetUnistallProgramsList()` like I did in the proof of concept above.

#### TODO:
- [ ] Figure out authentication
- [ ] Format Markdown from store description
   -   Requires also replacing `asset://` links with images. I think all the images id information are included in the store api JSON.
- [ ] Install links?
- [ ] Genre id numbers

**Comment by bburky** [comment]
Some more notes:

**Comment by bburky** [comment]
Some more notes:

I swear Ctrl+Alt+I used to work, but it doesn't seem to anymore. Access the Chrome DevTools by adding the following to the end of a file like `%APPDATA\Discord\0.0.305\modules\discord_voice\index.js`:

```
require('electron').remote.getCurrentWindow().openDevTools();
```

Last played information appears to be available in `https://discordapp.com/api/v6/users/@me/activities/statistics/applications`

The meaning of the list of genre numbers/enum exists only within the source of the JS discord application. I've extracted the enums from https://discordapp.com/assets/012d4cdfa848e4ebc4a2.js

**Comment by freaktechnik** [comment]
> I swear Ctrl+Alt+I used to work in the desktop Discord app

Pretty sure it only works on PTB or when dev mode is enabled these days.

**Comment by bburky** [comment]
Thanks @freaktechnik I didn't know that existed. For anyone else wondering PTB is apparently [Discord's public beta](https://discordia.me/ptb).

**Comment by ChildishGiant** [comment]
Ctrl+shift+i opens dev tools in the stable build

**Comment by JosefNemec** [comment]
I'm going to close this, Discord is clearly going away from selling games (they also dropped free Nitro game).

If anybody still needs this then it can be implemented as a custom library plugin.
